services:
  gameserver:
    build: /opt/enshrouded/Docker/enshrouded/
    container_name: gameix-enshrouded-gameserver
    image: gameix-enshrouded-gameserver:0.1.0
    ports:
      - "15636:15636/udp"
      - "15637:15637/udp"
    environment:
      - SERVER_NAME=GAMEIX.NET Enshrouded Server
      - SERVER_PASSWORD=WuppiDuppi12!
      - GAME_PORT=15636
      - QUERY_PORT=15637
      - SERVER_SLOTS=16
      - SERVER_IP=0.0.0.0
    volumes:
      - gameix-enshrouded-persistent-data:/home/steam
      - gameix-enshrouded-persistent-savegame:/home/steam/enshrouded/savegame

volumes:
  gameix-enshrouded-persistent-data:
  gameix-enshrouded-persistent-savegame:
  
  